[package]
name = "steel"
description = "Framework for building Solana programs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/regolith-labs/steel"
keywords = ["solana"]

[features]
deafult = []
spl = ["spl-token", "spl-associated-token-account"]

[dependencies]
bytemuck = "1.14.3"
solana-program = "^1.18"
spl-token = { version = "^4", features = ["no-entrypoint"], optional = true }
spl-associated-token-account = { version = "^2.3", features = [ "no-entrypoint" ], optional = true } 

